### ISSUE TITLE
User avatar fails on tlks.io if he changes it on Twitter

### ISSUE THREAD

**Issue by repejota** [tlksio/front#103]
If a user changes his own avatar on Twitter then fails when we try to show it as we are still looking on the previous image.

As a workaround, we can update user's profile when he sings-in again on our site because avatar URL is not an information hidden for us, but meanwhile the user does not signs-in on our site that avatar would be broken.

Any ideas on how to solve this?

PD: Found this because @octante changed his own avatar and now its broken for her :cry:

![screenshot from 2015-04-08 01 51 36](https://cloud.githubusercontent.com/assets/36673/7036213/d6c138b6-dd91-11e4-9b30-72d0188088fc.png)

**Comment by repejota** [comment]
WIP on [feature/103](https://github.com/tlksio/front/tree/feature/103)

**Comment by josgilmo** [comment]
It was solve by @repejota.
