### ISSUE TITLE
Add LinkedIn link social network on footer

### ISSUE THREAD

**Issue by repejota** [tlksio/front#106]
Add LinkedIn link social network on footer & create a profile for tlks.io as a company.

* That profile would be also used to publish talks for promotion. 
* Being a company will show everyone on the team as a workers on the project.

**Comment by repejota** [comment]
Mmmmm to create a LinkedIn company we must create before an email at something@tlks.io :angry:

**Comment by DawnAngel** [comment]
@repejota If you create the email and linkedin I will do the implementation.

**Comment by repejota** [comment]
I need to create a @tlks.io email. LinkedIn requires a correct email with our domain to create the company there and show its profile. Do you know any good free service to setup this?

**Comment by josgilmo** [comment]
I don'n know any service like that. I'm going to ask ...

**Comment by repejota** [comment]
Created a couple of forwards to myself.

hello@tlks.io
support@tlks.io
