### ISSUE TITLE
Do we need to put that annoying notice about cookies?

### ISSUE THREAD

**Issue by repejota** [tlksio/front#107]
We are not using own cookies but our site is sending them as we are using google analytics for example.

What do you think? Anyone knows how the law affect us?

![screenshot from 2015-04-08 02 41 47](https://cloud.githubusercontent.com/assets/36673/7036784/de7fab4e-dd98-11e4-9e6a-eb57619e1055.png)

**Comment by repejota** [comment]
For more information, Menéame has a link explaining a little bit more this topic:
https://www.meneame.net/legal#cookies

**Comment by DawnAngel** [comment]
This library from google looks nice for so reason:

**Comment by josgilmo** [comment]
If not for legislation, for giving information at our users I think that it's good to say that we are using Google Analytic,  and for that, using cookies.

I like the solution of @DawnAngel. If you are ok, we can create a new Issue for implement it (milestone 0.2)

**Comment by repejota** [comment]
:+1:

**Comment by repejota** [comment]
Moved to 0.2
