### ISSUE TITLE
Use smaller images on all lists

### ISSUE THREAD

**Issue by repejota** [tlksio/front#110]
By default we are using this URL to fetch the image for a talk:

`http://img.youtube.com/vi/<video-code>/0.jpg`

For example: http://img.youtube.com/vi/MeMPCSqQ-34/0.jpg

This image is 480x360px about 16KB, but Youtube has 4 different images being 0 the biggest one and 1,2 and 3 smaller ones.

For example: http://img.youtube.com/vi/MeMPCSqQ-34/2.jpg

Those smaller images are 120x90px about 4.8KB, and our current resolution is 175x134px. Maybe is better to use smaller ones?

What do you think?

**Comment by repejota** [comment]
I'm not sure because we are not serving those images, so the performance will be only to the client and we will not gain anything here.

**Comment by josgilmo** [comment]
For the size of thumbnails, we can read this: http://stackoverflow.com/questions/2068344/how-do-i-get-a-youtube-video-thumbnail-from-the-youtube-api.

I think that could be better solution for us to use the smaller image. Maybe tlks looks a wosrt, but for the user experience and SEO matters it's better solution.

**Comment by repejota** [comment]
So which url? http://img.youtube.com/vi/<insert-youtube-video-id-here>/default.jpg ?

And ... sorry but I like to know the reasons. Why its better for SEO?  
User experience may be something more related with taste ... but SEO is science not magic. :trollface: 

Please @josgilmo argument your response ;)

**Comment by repejota** [comment]
Using mqdefault on lists and hqdefault on shares.
