### ISSUE TITLE
Click on the video should increase number of views

### ISSUE THREAD

**Issue by repejota** [tlksio/front#119]
Clicking on the video embed to play the video inside the detailed view should increase the number of views? 
I'm not sure because:

* It seems that yes because if not we loose that view count.
* What happens if the user pauses/unpauses the video ... that is another view?
* Anyway ... despite my doubts. Is that possible? Which events provide this event widget?

**Comment by josgilmo** [comment]
I think that, only for cleaning the information, we shouldn't. 

Not sure if it is possible but keeping it's simple for us to track only for pageviews.

**Comment by repejota** [comment]
:+1:

**Comment by repejota** [comment]
Moved to 0.2

**Comment by repejota** [comment]
won't fix for now, a new roadmap is on its way
