### ISSUE TITLE
Implement following / followers

### ISSUE THREAD

**Issue by repejota** [tlksio/front#16]

**Comment by repejota** [comment]
http://www.graphstory.com/pricing.php it has a free service 20GB of data!

**Comment by repejota** [comment]
Another approache just with MongoDB http://stackoverflow.com/questions/14459194/mongodb-how-to-design-twitter-style-followers-following-relation-model-in-mongo

I also like the mention to flockdb ( which is used by Twitter )

**Comment by josgilmo** [comment]
In http://www.graphstory.com, I think node it's not supported...

Quoted from the 
"Use your language

Do you use PHP, Java, Python, 
C#, Swift, or Ruby?

What a coincidence! So do we."

**Comment by repejota** [comment]
https://github.com/thingdom/node-neo4j That's the nodejs client. And its just node.js but maybe you're right and they don't support node.js

Anyway ... int this case we can use another provider http://www.graphenedb.com/ who supports node.js

**Comment by repejota** [comment]
won't fix for now, A new roadmap is on its way
