### ISSUE TITLE
Error page on production

### ISSUE THREAD

**Issue by glopezdetorre** [tlksio/front#161]
Right now errors are shown as stack traces on prod, we should provide a proper error page for the users.

**Comment by repejota** [comment]
It was fixed long time ago at:

https://github.com/tlksio/front/blob/develop/index.js#L129

But seems to be broken. 

Also, that method only takes account HTTP500 errors, and sometimes the error occurs before, or simply it is not possible to trigger a proper HTTP error code.
It needs further improvement.

**Comment by repejota** [comment]
Errors are logged to /var/log/tlks.io/*.log in production and console in development.
