### ISSUE TITLE
Error messages on devel

### ISSUE THREAD

**Issue by glopezdetorre** [tlksio/front#162]
Node's stack trace is not very helpful when it comes to fixing an error on devel. We should look into some way to improve this.

**Comment by repejota** [comment]
A couple of links on how to handle errors properly on node.js and express:

http://expressjs.com/guide/error-handling.html
https://www.joyent.com/developers/node/design/errors

**Comment by repejota** [comment]
Errors and stacktrace are showed in console during development.
