### ISSUE TITLE
Sign-in with Twitter from the vote button results in 500 error page

### ISSUE THREAD

**Issue by glopezdetorre** [tlksio/front#186]
Reproduce:

Click on one of the talks linked from tlks.io twitter account. Push the vote button, Sign-in pop-up appears. Click on the Sign-in button and authorize application. You are taken to a 500 error page.

**Comment by repejota** [comment]
Ok ... tested it carefully.
Its not something about the OAuth code.

Its look like something about the session so you had a previous session on your laptop and your token expired ( I've logged, went to have a few beers and then was the moment I could reproduce the error).
If I close the browser, so the CSRF token is new everything works fine.

Nice bug @glopezdetorre a thought one to fix :facepunch:  needs to be debugged carefully to ensure I'm right.

Love you bitch! :girl:

**Comment by repejota** [comment]
Fixed!

**Comment by glopezdetorre** [comment]
I'm afraid I still can reproduce it from my phone :/

**Comment by repejota** [comment]
Phone?
Uhmmmmm thats curious :eyes:

**Comment by repejota** [comment]
Confirmed ... works on my desktop browser but fails on my phone too. Can you test please on your desktop?

**Comment by glopezdetorre** [comment]
On the desktop everything looks fine, it is just on my phone (Android Lollipop) that it fails. I'll try to do some more testing this afternoon and see if I find anything.

**Comment by glopezdetorre** [comment]
Oddly enough, apparently it works when tlks.io is opened in Chrome mobile, but it doesn't when the user clicks on a tlksio tweet inside the Twitter app (and thus tlksio is opened inside the app). I still have to do some more testing to verify this, though.

**Comment by repejota** [comment]
Fixed.
