### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by nataliobenitez** [tlksio/front#197]
You can not see info about talks language preferences either in the FAQ or in the video upload page. Can I upload talks in any language? Is english preferred? is ONLY english allowed?

If only english is allowed it should be clearly informed.
If any language is supported there could be two options:

weak: recommend to add a tag indicating the language (e.g. "Spanish").
strong: add a new field called "language" with the same level of importance as Url, Title, Description,...

**Comment by repejota** [comment]
As we try to be as much generic as we can we recommend all talks to be published in english.
Added a new question that explains it a little bit and suggests to add a tag if a different language talk is published.

PR: https://github.com/tlksio/front/pull/199

**Comment by repejota** [comment]
Reopen issue due I reverted the PR.
