### ISSUE TITLE
Paginate content on /activity page?

### ISSUE THREAD

**Issue by repejota** [tlksio/front#52]
Paginate? 
Continuous scroll?

**Comment by repejota** [comment]
That one was marked as a "question". I assume you're going to paginate it and remove its "question" label.

**Comment by josgilmo** [comment]
Yes, but when I learn how to remove label from github xDDDD

**Comment by repejota** [comment]
Hahaha! I've just did it for you :grimacing:

**Comment by repejota** [comment]
As we agreed with Jose this is not worth to fix. 
Next release will have following and followers for all users and activity will change to show only a log of events from our friends and not from all users.
