### ISSUE TITLE
Should we create a 403 Forbidden vs 401 Unauthorized template?

### ISSUE THREAD

**Issue by repejota** [tlksio/front#62]
What happens if a 403 Forbidden vs 401 Unauthorized HTTP error is produced? 

* Should we redirect the user to another page?
* Create a template?
* Warn him?

Let's discuss this here.

**Comment by repejota** [comment]
Currently we shows only "401" in case we go to http://localhost:8081/talk/add being an anonymous user.

**Comment by octante** [comment]
I think best option is show login page showing a message warning user is not logged.

**Comment by repejota** [comment]
@josgilmo any suggestions? How will be the process? 401 or 403? Then redirecting to login?

**Comment by repejota** [comment]
According to @josgilmo we should reply with a HTTP 401 code and show a template to inform the user that he is not authorized. 
This template must have links to login/home.

**Comment by josgilmo** [comment]
Thanks secretary xDDDD
