### ISSUE TITLE
Should we use a 404 template for non-found tags?

### ISSUE THREAD

**Issue by repejota** [tlksio/front#75]
For example:

Browing talks tagged as 'foobar' ( where 'foobar' is a tag that has not been yet created ):
http://localhost:8081/tag/foobar

 
![image](https://cloud.githubusercontent.com/assets/36673/6758208/d9dd8338-cf36-11e4-80fd-b58133ec8906.png)

It shows the "tag" template without talks/content. This is correct ofcourse, but it could not be desirable, for example @josgilmo it can harm SEO?.

So ... what's better here? show 404 error or leave this page without content?

**Comment by josgilmo** [comment]
I think that the best response it's a 204 according to http://tools.ietf.org/html/rfc2616#section-10.2.5.

**Comment by repejota** [comment]
:+1:

**Comment by repejota** [comment]
As it is decided, removing *question* and *hep wanted* tags.
