### ISSUE TITLE
Main navbar navigation and selected menu fails

### ISSUE THREAD

**Issue by repejota** [tlksio/front#88]
For example if i go to "Activity" it is still activated "Home" :sob: 

![image](https://cloud.githubusercontent.com/assets/36673/6876334/ac82b24c-d4c6-11e4-8b8d-398d6e245b42.png)

**Comment by DawnAngel** [comment]
What do you think off this solution? @repejota

**Comment by repejota** [comment]
:+1: 
As I said on the merge request for me it is OK. Just finish the work with the other links and merge the changes!
