### ISSUE TITLE
Debate about to include the name of uploader

### ISSUE THREAD

**Issue by octante** [tlksio/front#98]
We can debate if put the user that has upload the talk can be useful. In future we can make user ranks, and so one.

This data can be included in talk page.

**Comment by repejota** [comment]
Here is an screenshot about how producthunt.com does this:

![image](https://cloud.githubusercontent.com/assets/36673/6906392/e6d23a16-d72e-11e4-9f12-f4d2c4a7d1ca.png)

So my vote is :+1:,  it would be nice.

**Comment by octante** [comment]
Uou! very nice design! :)

**Comment by repejota** [comment]
Already did on 0.1.0
