### ISSUE TITLE
Include commentaries

### ISSUE THREAD

**Issue by octante** [tlksio/front#99]
Include commentaries in talks to add more value and increase unique content. @josgilmo is it important for seo? for user can be useful, but maybe for seo too.

**Comment by repejota** [comment]
This is a bug!! 
I was using disqus ( http://disqus.com ) for the comments. And for some reason is broken.

**Comment by octante** [comment]
uops! ok, so we can put in milestone 0.1.0. Is a pity if not works.

**Comment by DawnAngel** [comment]
I will take a look tomorrow, because I know disqus a lot, "chromecast" you know...

**Comment by repejota** [comment]
Thsnks mate!

**Comment by octante** [comment]
Cool!!! :D
